name: chatbot
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  get_it: ^7.6.0
  image_picker: ^1.0.7
  injectable: ^2.1.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^1.3.0
  retrofit: ^4.0.1
  shared_preferences: ^2.1.1
  web_socket_channel: ^2.2.0
  uuid: ^3.0.4
  flutter_chat_types: ^3.6.2
  file_picker: ^4.2.7
  flutter_spinkit: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
